#1.0 IMPORTING THE LIBRARIES

In [ ]:
# Importing the pandas library
import pandas as pd

# Importing the numpy library
import numpy as np

#2.0 DATA LOADING AND CLEANING.

In [ ]:
#First load the bitcoin data and preview records 
bitcoin_data = pd.read_csv('/content/bitcoin.csv')
bitcoin_data.head()

         Date         Open         High  ...        Close    Adj Close     Volume
0  2017-02-21  1079.280029  1117.250000  ...  1115.300049  1115.300049  186868992
1  2017-02-22  1114.800049  1125.390015  ...  1117.439941  1117.439941  136100000
2  2017-02-23  1117.270020  1176.619995  ...  1166.719971  1166.719971  189454000
3  2017-02-24  1172.709961  1200.390015  ...  1173.680054  1173.680054  330759008
4  2017-02-25  1170.410034  1174.849976  ...  1143.839966  1143.839966  139960992

[5 rows x 7 columns]

In [ ]:
#Load the ethereum data and preview records 
ethereum_data = pd.read_csv('/content/ethereum.csv')
ethereum_data.head()

         Date        Open        High  ...       Close   Adj Close      Volume
0  2017-11-09  308.644989  329.451996  ...  320.884003  320.884003   893249984
1  2017-11-10  320.670990  324.717987  ...  299.252991  299.252991   885985984
2  2017-11-11  298.585999  319.453003  ...  314.681000  314.681000   842300992
3  2017-11-12  314.690002  319.153015  ...  307.907990  307.907990  1613479936
4  2017-11-13  307.024994  328.415009  ...  316.716003  316.716003  1041889984

[5 rows x 7 columns]

In [ ]:
#Get information about our datasets
bitcoin_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1827 entries, 0 to 1826
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       1827 non-null   object
 1   Open       1827 non-null   float64
 2   High       1827 non-null   float64
 3   Low        1827 non-null   float64
 4   Close      1827 non-null   float64
 5   Adj Close  1827 non-null   float64
 6   Volume     1827 non-null   int64
dtypes: float64(5), int64(1), object(1)
memory usage: 100.0+ KB

In [ ]:
ethereum_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1566 entries, 0 to 1565
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       1566 non-null   object
 1   Open       1566 non-null   float64
 2   High       1566 non-null   float64
 3   Low        1566 non-null   float64
 4   Close      1566 non-null   float64
 5   Adj Close  1566 non-null   float64
 6   Volume     1566 non-null   int64
dtypes: float64(5), int64(1), object(1)
memory usage: 85.8+ KB

In [ ]:
#separating the columns in the bitcoin data
bitcoin_data = pd.read_csv('/content/bitcoin.csv', sep = ',')
bitcoin_data.head()

         Date         Open         High  ...        Close    Adj Close     Volume
0  2017-02-21  1079.280029  1117.250000  ...  1115.300049  1115.300049  186868992
1  2017-02-22  1114.800049  1125.390015  ...  1117.439941  1117.439941  136100000
2  2017-02-23  1117.270020  1176.619995  ...  1166.719971  1166.719971  189454000
3  2017-02-24  1172.709961  1200.390015  ...  1173.680054  1173.680054  330759008
4  2017-02-25  1170.410034  1174.849976  ...  1143.839966  1143.839966  139960992

[5 rows x 7 columns]

In [ ]:
ethereum_data = pd.read_csv('/content/ethereum.csv', sep = ',')
ethereum_data.head()

         Date        Open        High  ...       Close   Adj Close      Volume
0  2017-11-09  308.644989  329.451996  ...  320.884003  320.884003   893249984
1  2017-11-10  320.670990  324.717987  ...  299.252991  299.252991   885985984
2  2017-11-11  298.585999  319.453003  ...  314.681000  314.681000   842300992
3  2017-11-12  314.690002  319.153015  ...  307.907990  307.907990  1613479936
4  2017-11-13  307.024994  328.415009  ...  316.716003  316.716003  1041889984

[5 rows x 7 columns]

In [ ]:
#Get information about the dataset again to see if changes are effective.
bitcoin_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1827 entries, 0 to 1826
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       1827 non-null   object
 1   Open       1827 non-null   float64
 2   High       1827 non-null   float64
 3   Low        1827 non-null   float64
 4   Close      1827 non-null   float64
 5   Adj Close  1827 non-null   float64
 6   Volume     1827 non-null   int64
dtypes: float64(5), int64(1), object(1)
memory usage: 100.0+ KB

In [ ]:
#Get information about the dataset again to see if changes are effective.
ethereum_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1566 entries, 0 to 1565
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       1566 non-null   object
 1   Open       1566 non-null   float64
 2   High       1566 non-null   float64
 3   Low        1566 non-null   float64
 4   Close      1566 non-null   float64
 5   Adj Close  1566 non-null   float64
 6   Volume     1566 non-null   int64
dtypes: float64(5), int64(1), object(1)
memory usage: 85.8+ KB

From the above info we'll change the Date column from object data type to date/time.

In [ ]:
#Changing the Date column's data type from object to date/time.
bitcoin_data['Date'] = pd.to_datetime(bitcoin_data['Date'])
bitcoin_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1827 entries, 0 to 1826
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       1827 non-null   datetime64[ns]
 1   Open       1827 non-null   float64
 2   High       1827 non-null   float64
 3   Low        1827 non-null   float64
 4   Close      1827 non-null   float64
 5   Adj Close  1827 non-null   float64
 6   Volume     1827 non-null   int64
dtypes: datetime64[ns](1), float64(5), int64(1)
memory usage: 100.0 KB

In [ ]:
#Changing the Date column's data type from object to date/time.
ethereum_data['Date'] = pd.to_datetime(ethereum_data['Date'])
ethereum_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1566 entries, 0 to 1565
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       1566 non-null   datetime64[ns]
 1   Open       1566 non-null   float64
 2   High       1566 non-null   float64
 3   Low        1566 non-null   float64
 4   Close      1566 non-null   float64
 5   Adj Close  1566 non-null   float64
 6   Volume     1566 non-null   int64
dtypes: datetime64[ns](1), float64(5), int64(1)
memory usage: 85.8 KB

In [ ]:
#Ensure uniformity by changing the column names to lower case, stripping of the whitespaces,removing periods, 
#this ensures good readerbility plus every naming issue is covered.
#This is to be applied to both the bitcoin and ethereum datasets.
#Bitcoin dataset

bitcoin_data.columns = bitcoin_data.columns.str.lower().str.strip().str.replace(' ', '_').str.replace('.', '')
bitcoin_data.columns

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.

Index(['date', 'open', 'high', 'low', 'close', 'adj_close', 'volume'], dtype='object')

In [ ]:
#Ethereum dataset
ethereum_data.columns = ethereum_data.columns.str.lower().str.strip().str.replace(' ', '_').str.replace('.', '')
ethereum_data.columns

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.

Index(['date', 'open', 'high', 'low', 'close', 'adj_close', 'volume'], dtype='object')

In [ ]:
#Renaming the columns in both our datasets to differentiate between the bitcoin and ethereum columns by adding an 'eth' suffix for ethereum
#and a 'bit' for bitcoin.
bitcoin_data2 = bitcoin_data.add_suffix('bit')

In [ ]:
#repeat the process for ethereum dataset

ethereum_data2 =ethereum_data.add_suffix('eth')

In [ ]:
bitcoin_data2.head()

     datebit      openbit      highbit  ...     closebit  adj_closebit  volumebit
0 2017-02-21  1079.280029  1117.250000  ...  1115.300049   1115.300049  186868992
1 2017-02-22  1114.800049  1125.390015  ...  1117.439941   1117.439941  136100000
2 2017-02-23  1117.270020  1176.619995  ...  1166.719971   1166.719971  189454000
3 2017-02-24  1172.709961  1200.390015  ...  1173.680054   1173.680054  330759008
4 2017-02-25  1170.410034  1174.849976  ...  1143.839966   1143.839966  139960992

[5 rows x 7 columns]

In [ ]:
ethereum_data2.head()

     dateeth     openeth     higheth  ...    closeeth  adj_closeeth   volumeeth
0 2017-11-09  308.644989  329.451996  ...  320.884003    320.884003   893249984
1 2017-11-10  320.670990  324.717987  ...  299.252991    299.252991   885985984
2 2017-11-11  298.585999  319.453003  ...  314.681000    314.681000   842300992
3 2017-11-12  314.690002  319.153015  ...  307.907990    307.907990  1613479936
4 2017-11-13  307.024994  328.415009  ...  316.716003    316.716003  1041889984

[5 rows x 7 columns]

In [ ]:
#renaming the 'dateeth' column to 'datebit' to be able to merge the two datasets since the data was collected in the same period.

ethereum_data3 = ethereum_data2.rename(columns={'dateeth': 'datebit'}, inplace=True)

In [ ]:
ethereum_data2

        datebit      openeth  ...  adj_closeeth    volumeeth
0    2017-11-09   308.644989  ...    320.884003    893249984
1    2017-11-10   320.670990  ...    299.252991    885985984
2    2017-11-11   298.585999  ...    314.681000    842300992
3    2017-11-12   314.690002  ...    307.907990   1613479936
4    2017-11-13   307.024994  ...    316.716003   1041889984
...         ...          ...  ...           ...          ...
1561 2022-02-17  3126.858398  ...   2881.481934  15860206214
1562 2022-02-18  2884.340576  ...   2785.727539  15748173433
1563 2022-02-19  2784.872803  ...   2763.701172   9774183169
1564 2022-02-20  2763.756592  ...   2628.648438  11641437834
1565 2022-02-21  2620.029541  ...   2599.479980  13132299264

[1566 rows x 7 columns]

#Merging the datasets

In [ ]:
# creating a new data set by combining the Bitcoin and Ethereum datasets and displaying it.

crypto_data = pd.merge(bitcoin_data2, ethereum_data2, left_on='datebit', right_on='datebit')
crypto_data

        datebit       openbit  ...  adj_closeeth    volumeeth
0    2017-11-09   7446.830078  ...    320.884003    893249984
1    2017-11-10   7173.729980  ...    299.252991    885985984
2    2017-11-11   6618.609863  ...    314.681000    842300992
3    2017-11-12   6295.450195  ...    307.907990   1613479936
4    2017-11-13   5938.250000  ...    316.716003   1041889984
...         ...           ...  ...           ...          ...
1561 2022-02-17  43937.070313  ...   2881.481934  15860206214
1562 2022-02-18  40552.132813  ...   2785.727539  15748173433
1563 2022-02-19  40026.023438  ...   2763.701172   9774183169
1564 2022-02-20  40118.101563  ...   2628.648438  11641437834
1565 2022-02-21  38339.218750  ...   2599.479980  13132299264

[1566 rows x 13 columns]

In [ ]:
#Checking the info again
crypto_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1566 entries, 0 to 1565
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   datebit       1566 non-null   datetime64[ns]
 1   openbit       1566 non-null   float64
 2   highbit       1566 non-null   float64
 3   lowbit        1566 non-null   float64
 4   closebit      1566 non-null   float64
 5   adj_closebit  1566 non-null   float64
 6   volumebit     1566 non-null   int64
 7   openeth       1566 non-null   float64
 8   higheth       1566 non-null   float64
 9   loweth        1566 non-null   float64
 10  closeeth      1566 non-null   float64
 11  adj_closeeth  1566 non-null   float64
 12  volumeeth     1566 non-null   int64
dtypes: datetime64[ns](1), float64(10), int64(2)
memory usage: 171.3 KB

After checking, there are no null values since the non-null count for each column = the total entries i.e 1554

In [ ]:
#Dropping the unnecessary columns 'closebit' and 'closeeth' since we can use 'adj_closebit' and 'adj_closeeth' which more conclusive figures.

crypto_data.drop(["closebit" , "closeeth"], axis = 1, inplace = True)
crypto_data.head(10)

     datebit      openbit      highbit  ...      loweth  adj_closeeth   volumeeth
0 2017-11-09  7446.830078  7446.830078  ...  307.056000    320.884003   893249984
1 2017-11-10  7173.729980  7312.000000  ...  294.541992    299.252991   885985984
2 2017-11-11  6618.609863  6873.149902  ...  298.191986    314.681000   842300992
3 2017-11-12  6295.450195  6625.049805  ...  298.513000    307.907990  1613479936
4 2017-11-13  5938.250000  6811.189941  ...  307.024994    316.716003  1041889984
5 2017-11-14  6561.479980  6764.979980  ...  316.763000    337.631012  1069680000
6 2017-11-15  6634.759766  7342.250000  ...  329.812988    333.356995   722665984
7 2017-11-16  7323.240234  7967.379883  ...  323.605988    330.924011   797254016
8 2017-11-17  7853.569824  8004.589844  ...  327.523010    332.394012   621732992
9 2017-11-18  7697.209961  7884.990234  ...  327.687012    347.612000   649638976

[10 rows x 11 columns]

In [ ]:
#Check Consistency and remove duplicated date records
crypto_data.drop_duplicates(subset=['datebit'])

        datebit       openbit  ...  adj_closeeth    volumeeth
0    2017-11-09   7446.830078  ...    320.884003    893249984
1    2017-11-10   7173.729980  ...    299.252991    885985984
2    2017-11-11   6618.609863  ...    314.681000    842300992
3    2017-11-12   6295.450195  ...    307.907990   1613479936
4    2017-11-13   5938.250000  ...    316.716003   1041889984
...         ...           ...  ...           ...          ...
1561 2022-02-17  43937.070313  ...   2881.481934  15860206214
1562 2022-02-18  40552.132813  ...   2785.727539  15748173433
1563 2022-02-19  40026.023438  ...   2763.701172   9774183169
1564 2022-02-20  40118.101563  ...   2628.648438  11641437834
1565 2022-02-21  38339.218750  ...   2599.479980  13132299264

[1566 rows x 11 columns]

In [ ]:
#Exporting our new clean and merged dataset to a single csv file.
crypto_data.to_csv("crypto_dataset.csv", index=False)

In [ ]:
# Lets read our dataset from our CSV file and create a dataframe that we will use
crypto_df=pd.read_csv('crypto_dataset.csv')

In [ ]:
# Let's Preview the first 10 records of our cleaned DataFrame 

crypto_df.head(10)

      datebit      openbit      highbit  ...      loweth  adj_closeeth   volumeeth
0  2017-11-09  7446.830078  7446.830078  ...  307.056000    320.884003   893249984
1  2017-11-10  7173.729980  7312.000000  ...  294.541992    299.252991   885985984
2  2017-11-11  6618.609863  6873.149902  ...  298.191986    314.681000   842300992
3  2017-11-12  6295.450195  6625.049805  ...  298.513000    307.907990  1613479936
4  2017-11-13  5938.250000  6811.189941  ...  307.024994    316.716003  1041889984
5  2017-11-14  6561.479980  6764.979980  ...  316.763000    337.631012  1069680000
6  2017-11-15  6634.759766  7342.250000  ...  329.812988    333.356995   722665984
7  2017-11-16  7323.240234  7967.379883  ...  323.605988    330.924011   797254016
8  2017-11-17  7853.569824  8004.589844  ...  327.523010    332.394012   621732992
9  2017-11-18  7697.209961  7884.990234  ...  327.687012    347.612000   649638976

[10 rows x 11 columns]

In [ ]:
# Let's Preview the last 10 records of our cleaned DataFrame 

crypto_df.tail(10)

         datebit       openbit  ...  adj_closeeth    volumeeth
1556  2022-02-12  42412.300781  ...   2917.362793  11254355757
1557  2022-02-13  42236.566406  ...   2883.463379   9054963563
1558  2022-02-14  42157.398438  ...   2933.479004  12164552172
1559  2022-02-15  42586.464844  ...   3179.877197  13921257873
1560  2022-02-16  44578.277344  ...   3127.830078  12352406833
1561  2022-02-17  43937.070313  ...   2881.481934  15860206214
1562  2022-02-18  40552.132813  ...   2785.727539  15748173433
1563  2022-02-19  40026.023438  ...   2763.701172   9774183169
1564  2022-02-20  40118.101563  ...   2628.648438  11641437834
1565  2022-02-21  38339.218750  ...   2599.479980  13132299264

[10 rows x 11 columns]

#3.0 DATA ANALYSIS

From this dataset, we want to able to derive meaningful Analysis that will guide the decision of a future Cryptocurrency Invest. As such, below is our Analysis.

###1.What has been the Highest Price of the two currencies in comparison (Bitcoin and Etherium) over the 5 years?

In [ ]:
# Let's find the 10 most highest prices with their corresponding dates for the Bitcoin trade over the last 5 years

bitcoin_highest_trade=crypto_df[(crypto_df['datebit'] <= '21-02-2022') & (crypto_df['datebit'] >= '09-11-2017')].nlargest(10, ['highbit'])[['datebit','highbit']]
bitcoin_highest_trade

         datebit       highbit
1462  2021-11-10  68789.625000
1461  2021-11-09  68530.335938
1460  2021-11-08  67673.742188
1441  2021-10-20  66930.390625
1442  2021-10-21  66600.546875
1467  2021-11-15  66281.570313
1463  2021-11-11  65579.015625
1466  2021-11-14  65495.179688
1464  2021-11-12  65460.816406
1465  2021-11-13  64915.675781

In [ ]:
# Let's find the 10 most highest prices with their corresponding dates for the Etherium trade over the last 5 years

etherium_highest_trade=crypto_df[(crypto_df['datebit'] <= '21-02-2022') & (crypto_df['datebit'] >= '09-11-2017')].nlargest(10, ['higheth'])[['datebit','higheth']]
etherium_highest_trade

         datebit      higheth
1468  2021-11-16  4891.704590
1462  2021-11-10  4859.502930
1461  2021-11-09  4837.589355
1460  2021-11-08  4822.363281
1464  2021-11-12  4808.738770
1483  2021-12-01  4780.732422
1463  2021-11-11  4778.059082
1467  2021-11-15  4764.636230
1482  2021-11-30  4753.266113
1465  2021-11-13  4702.115234

###2.What has been the Lowest Price of the two currencies in comparison (Bitcoin and Etherium)

In [ ]:
# Let's find the 10 most lowest prices with their corresponding dates for the Bitcoin trade over the last 5 years

bitcoin_lowest_trade=crypto_df[(crypto_df['datebit'] <= '21-02-2022') & (crypto_df['datebit'] >= '09-11-2017')].nsmallest(10, ['lowbit'])[['datebit','lowbit']]
bitcoin_lowest_trade

        datebit       lowbit
401  2018-12-15  3191.303467
400  2018-12-14  3206.542236
402  2018-12-16  3233.819824
403  2018-12-17  3253.123047
393  2018-12-07  3280.228760
399  2018-12-13  3298.132080
394  2018-12-08  3350.650635
456  2019-02-08  3391.023682
397  2018-12-11  3392.250000
455  2019-02-07  3394.218506

In [ ]:
# Let's find the 10 most lowest prices with their corresponding dates for the Etherium trade over the last 5 years

etherium_lowest_trade=crypto_df[(crypto_df['datebit'] <= '21-02-2022') & (crypto_df['datebit'] >= '09-11-2017')].nsmallest(10, ['loweth'])[['datebit','loweth']]
etherium_lowest_trade

        datebit     loweth
401  2018-12-15  82.829887
400  2018-12-14  83.226479
393  2018-12-07  83.469719
402  2018-12-16  84.469406
403  2018-12-17  85.382111
399  2018-12-13  85.518311
394  2018-12-08  86.825668
397  2018-12-11  87.688408
398  2018-12-12  88.263557
396  2018-12-10  90.654251

###3.What has been the Highest Volume traded for the two currencies in comparison (Bitcoin and Etherium) over the past 5 years

In [ ]:
# Let's find the 10 most highest volumes with their corresponding dates for the Bitcoin trade over the last 5 years

bitcoin_highest_volume=crypto_df[(crypto_df['datebit'] <= '21-02-2022') & (crypto_df['datebit'] >= '09-11-2017')].nlargest(10, ['volumebit'])[['datebit','volumebit']]
bitcoin_highest_volume

         datebit     volumebit
1205  2021-02-26  350967941479
1287  2021-05-19  126358098747
1159  2021-01-11  123320567399
1177  2021-01-29  117894572511
1202  2021-02-23  106102492824
1187  2021-02-08  101467222687
1256  2021-04-18   97468872758
1281  2021-05-13   96721152926
1201  2021-02-22   92052420332
1188  2021-02-09   91809846886

In [ ]:
# Let's find the 10 most highest volumes with their corresponding dates for the Etherium trade over the last 5 years

etherium_highest_volume=crypto_df[(crypto_df['datebit'] <= '21-02-2022') & (crypto_df['datebit'] >= '09-11-2017')].nlargest(10, ['volumeeth'])[['datebit','volumeeth']]
etherium_highest_volume

         datebit    volumeeth
1287  2021-05-19  84482912776
1281  2021-05-13  78398214539
1280  2021-05-12  69023382175
1288  2021-05-20  67610826680
1278  2021-05-10  62691789007
1272  2021-05-04  62402045158
1159  2021-01-11  60733630300
1152  2021-01-04  56945985763
1291  2021-05-23  56005721977
1261  2021-04-23  55413933925

###4.What has been the Lowest Volume traded for the two currencies in comparison (Bitcoin and Etherium) over the past 5 years

In [ ]:
# Let's find the 10 most lowest volumes with their corresponding dates for the Bitcoin trade over the last 5 years

bitcoin_lowest_volume=crypto_df[(crypto_df['datebit'] <= '21-02-2022') & (crypto_df['datebit'] >= '09-11-2017')].nsmallest(10, ['volumebit'])[['datebit','volumebit']]
bitcoin_lowest_volume

        datebit   volumebit
247  2018-07-14  2923670016
338  2018-10-13  3064030000
339  2018-10-14  3085320000
220  2018-06-17  3104019968
10   2017-11-19  3149319936
219  2018-06-16  3194170112
5    2017-11-14  3197110016
310  2018-09-15  3216300000
0    2017-11-09  3226249984
350  2018-10-25  3230550000

In [ ]:
# Let's find the 10 most lowest volumes with their corresponding dates for the Etherium trade over the last 5 years

etherium_lowest_volume=crypto_df[(crypto_df['datebit'] <= '21-02-2022') & (crypto_df['datebit'] >= '09-11-2017')].nsmallest(10, ['volumeeth'])[['datebit','volumeeth']]
etherium_lowest_volume

       datebit  volumeeth
8   2017-11-17  621732992
9   2017-11-18  649638976
6   2017-11-15  722665984
7   2017-11-16  797254016
13  2017-11-22  800819008
11  2017-11-20  807027008
2   2017-11-11  842300992
1   2017-11-10  885985984
0   2017-11-09  893249984
23  2017-12-02  943649984

###5.What has been the percentage increase in price for the two currencies in comparison (Bitcoin and Etherium) over the past 5 years

In [ ]:
# Let's start by previewing the start and end highbit value of bitcoin in every year for the past 5 years.

range1=crypto_df[(crypto_df['datebit'] >= '2017-11-09') & (crypto_df['datebit'] <= '2018-11-09')].iloc[[0,-1]][['datebit','highbit']]
print(range1)
range2=crypto_df[(crypto_df['datebit'] > '2018-11-09') & (crypto_df['datebit'] <= '2019-11-09')].iloc[[0,-1]][['datebit','highbit']]
print(range2)
range3=crypto_df[(crypto_df['datebit'] > '2019-11-09') & (crypto_df['datebit'] <= '2020-11-09')].iloc[[0,-1]][['datebit','highbit']]
print(range3)
range4=crypto_df[(crypto_df['datebit'] > '2020-11-09') & (crypto_df['datebit'] <= '2021-11-09')].iloc[[0,-1]][['datebit','highbit']]
print(range4)
range5=crypto_df[(crypto_df['datebit'] > '2021-11-09') & (crypto_df['datebit'] <= '2022-11-21')].iloc[[0,-1]][['datebit','highbit']]
print(range5)

        datebit      highbit
0    2017-11-09  7446.830078
365  2018-11-09  6456.459961
        datebit      highbit
366  2018-11-10  6437.279785
730  2019-11-09  8891.818359
         datebit       highbit
731   2019-11-10   9103.826172
1096  2020-11-09  15785.136719
         datebit       highbit
1097  2020-11-10  15450.329102
1461  2021-11-09  68530.335938
         datebit       highbit
1462  2021-11-10  68789.625000
1565  2022-02-21  39379.757813

In [ ]:
from tabulate import tabulate
range1['Bitcoin Price Difference'] = range1['highbit'].diff(periods=1)

range2['Bitcoin Price Difference'] = range2['highbit'].diff(periods=1)

range3['Bitcoin Price Difference'] = range3['highbit'].diff(periods=1)

range4['Bitcoin Price Difference'] = range4['highbit'].diff(periods=1)

range5['Bitcoin Price Difference'] = range5['highbit'].diff(periods=1)

range1['Bitcoin Price % Profit/Loss'] = ((range1['Bitcoin Price Difference']/7446.83)*100)

range2['Bitcoin Price % Profit/Loss'] = ((range2['Bitcoin Price Difference']/6437.28)*100)

range3['Bitcoin Price % Profit/Loss'] = ((range3['Bitcoin Price Difference']/9103.83)*100)

range4['Bitcoin Price % Profit/Loss'] = ((range4['Bitcoin Price Difference']/15450.3)*100)

range5['Bitcoin Price % Profit/Loss'] = ((range5['Bitcoin Price Difference']/68789.63)*100)

print(tabulate(range1, headers='keys', tablefmt='psql'))
print(tabulate(range2, headers='keys', tablefmt='psql'))
print(tabulate(range3, headers='keys', tablefmt='psql'))
print(tabulate(range4, headers='keys', tablefmt='psql'))
print(tabulate(range5, headers='keys', tablefmt='psql'))

+-----+------------+-----------+----------------------------+-------------------------------+
|     | datebit    |   highbit |   Bitcoin Price Difference |   Bitcoin Price % Profit/Loss |
|-----+------------+-----------+----------------------------+-------------------------------|
|   0 | 2017-11-09 |   7446.83 |                     nan    |                      nan      |
| 365 | 2018-11-09 |   6456.46 |                    -990.37 |                      -13.2992 |
+-----+------------+-----------+----------------------------+-------------------------------+
+-----+------------+-----------+----------------------------+-------------------------------+
|     | datebit    |   highbit |   Bitcoin Price Difference |   Bitcoin Price % Profit/Loss |
|-----+------------+-----------+----------------------------+-------------------------------|
| 366 | 2018-11-10 |   6437.28 |                     nan    |                      nan      |
| 730 | 2019-11-09 |   8891.82 |                    2454.54 |                       38.1301 |
+-----+------------+-----------+----------------------------+-------------------------------+
+------+------------+-----------+----------------------------+-------------------------------+
|      | datebit    |   highbit |   Bitcoin Price Difference |   Bitcoin Price % Profit/Loss |
|------+------------+-----------+----------------------------+-------------------------------|
|  731 | 2019-11-10 |   9103.83 |                     nan    |                      nan      |
| 1096 | 2020-11-09 |  15785.1  |                    6681.31 |                       73.3901 |
+------+------------+-----------+----------------------------+-------------------------------+
+------+------------+-----------+----------------------------+-------------------------------+
|      | datebit    |   highbit |   Bitcoin Price Difference |   Bitcoin Price % Profit/Loss |
|------+------------+-----------+----------------------------+-------------------------------|
| 1097 | 2020-11-10 |   15450.3 |                        nan |                       nan     |
| 1461 | 2021-11-09 |   68530.3 |                      53080 |                       343.553 |
+------+------------+-----------+----------------------------+-------------------------------+
+------+------------+-----------+----------------------------+-------------------------------+
|      | datebit    |   highbit |   Bitcoin Price Difference |   Bitcoin Price % Profit/Loss |
|------+------------+-----------+----------------------------+-------------------------------|
| 1462 | 2021-11-10 |   68789.6 |                      nan   |                      nan      |
| 1565 | 2022-02-21 |   39379.8 |                   -29409.9 |                      -42.7533 |
+------+------------+-----------+----------------------------+-------------------------------+

As per the data above, all the negative values indicate a price drop, hence a loss. The positive values, on the other hand, indicate a price increase, hence a profit. This analysis is done for the opening value and closing value of Bitcoin for every year for the period of five years.

From the Analysis above, Bitcoin experience the highest profit of 344% between 10-11-2020 and 09-11-21. It can also been concluded that Bitcoin experince the greatest loss between 10-11-2021 and 21-02-2022, which translated to 43% loss.

In [ ]:
# Let's start by previewing the start and end highbit value of etherium every year for the past 5 years.

range_eth1=crypto_df[(crypto_df['datebit'] <= '2018-11-09') & (crypto_df['datebit'] >= '2017-11-09')].iloc[[0,-1]][['datebit','higheth']]
print(range_eth1)
range_eth2=crypto_df[(crypto_df['datebit'] <= '2019-11-09') & (crypto_df['datebit'] > '2018-11-09')].iloc[[0,-1]][['datebit','higheth']]
print(range_eth2)
range_eth3=crypto_df[(crypto_df['datebit'] <= '2020-11-09') & (crypto_df['datebit'] > '2019-11-09')].iloc[[0,-1]][['datebit','higheth']]
print(range_eth3)
range_eth4=crypto_df[(crypto_df['datebit'] <= '2021-11-09') & (crypto_df['datebit'] > '2020-11-09')].iloc[[0,-1]][['datebit','higheth']]
print(range_eth4)
range_eth5=crypto_df[(crypto_df['datebit'] <= '2022-11-21') & (crypto_df['datebit'] > '2021-11-09')].iloc[[0,-1]][['datebit','higheth']]
print(range_eth5)

        datebit     higheth
0    2017-11-09  329.451996
365  2018-11-09  213.315994
        datebit     higheth
366  2018-11-10  213.856995
730  2019-11-09  185.838531
         datebit     higheth
731   2019-11-10  190.920609
1096  2020-11-09  457.349609
         datebit      higheth
1097  2020-11-10   453.758362
1461  2021-11-09  4837.589355
         datebit      higheth
1462  2021-11-10  4859.502930
1565  2022-02-21  2750.815918

In [ ]:
from tabulate import tabulate
range_eth1['Etherium Price Difference'] = range_eth1['higheth'].diff(periods=1)

range_eth2['Etherium Price Difference'] = range_eth2['higheth'].diff(periods=1)

range_eth3['Etherium Price Difference'] = range_eth3['higheth'].diff(periods=1)

range_eth4['Etherium Price Difference'] = range_eth4['higheth'].diff(periods=1)

range_eth5['Etherium Price Difference'] = range_eth5['higheth'].diff(periods=1)

range_eth1['Etherium Price % Profit/Loss'] = ((range_eth1['Etherium Price Difference']/329.45)*100)

range_eth2['Etherium Price % Profit/Loss'] = ((range_eth2['Etherium Price Difference']/213.86)*100)

range_eth3['Etherium Price % Profit/Loss'] = ((range_eth3['Etherium Price Difference']/190.92)*100)

range_eth4['Etherium Price % Profit/Loss'] = ((range_eth4['Etherium Price Difference']/453.76)*100)

range_eth5['Etherium Price % Profit/Loss'] = ((range_eth5['Etherium Price Difference']/4859.50)*100)


print(tabulate(range_eth1, headers='keys', tablefmt='psql'))
print(tabulate(range_eth2, headers='keys', tablefmt='psql'))
print(tabulate(range_eth3, headers='keys', tablefmt='psql'))
print(tabulate(range_eth4, headers='keys', tablefmt='psql'))
print(tabulate(range_eth5, headers='keys', tablefmt='psql'))

+-----+------------+-----------+-----------------------------+--------------------------------+
|     | datebit    |   higheth |   Etherium Price Difference |   Etherium Price % Profit/Loss |
|-----+------------+-----------+-----------------------------+--------------------------------|
|   0 | 2017-11-09 |   329.452 |                     nan     |                       nan      |
| 365 | 2018-11-09 |   213.316 |                    -116.136 |                       -35.2515 |
+-----+------------+-----------+-----------------------------+--------------------------------+
+-----+------------+-----------+-----------------------------+--------------------------------+
|     | datebit    |   higheth |   Etherium Price Difference |   Etherium Price % Profit/Loss |
|-----+------------+-----------+-----------------------------+--------------------------------|
| 366 | 2018-11-10 |   213.857 |                    nan      |                       nan      |
| 730 | 2019-11-09 |   185.839 |                    -28.0185 |                       -13.1013 |
+-----+------------+-----------+-----------------------------+--------------------------------+
+------+------------+-----------+-----------------------------+--------------------------------+
|      | datebit    |   higheth |   Etherium Price Difference |   Etherium Price % Profit/Loss |
|------+------------+-----------+-----------------------------+--------------------------------|
|  731 | 2019-11-10 |   190.921 |                     nan     |                         nan    |
| 1096 | 2020-11-09 |   457.35  |                     266.429 |                         139.55 |
+------+------------+-----------+-----------------------------+--------------------------------+
+------+------------+-----------+-----------------------------+--------------------------------+
|      | datebit    |   higheth |   Etherium Price Difference |   Etherium Price % Profit/Loss |
|------+------------+-----------+-----------------------------+--------------------------------|
| 1097 | 2020-11-10 |   453.758 |                      nan    |                        nan     |
| 1461 | 2021-11-09 |  4837.59  |                     4383.83 |                        966.112 |
+------+------------+-----------+-----------------------------+--------------------------------+
+------+------------+-----------+-----------------------------+--------------------------------+
|      | datebit    |   higheth |   Etherium Price Difference |   Etherium Price % Profit/Loss |
|------+------------+-----------+-----------------------------+--------------------------------|
| 1462 | 2021-11-10 |   4859.5  |                      nan    |                       nan      |
| 1565 | 2022-02-21 |   2750.82 |                    -2108.69 |                       -43.3931 |
+------+------------+-----------+-----------------------------+--------------------------------+

As per the data above, all the negative values indicate a price drop, hence a loss. The positive values, on the other hand, indicate a price increase, hence a profit. This analysis is done for the opening value and closing value of Etherium for every year for the period of five years.

From the Analysis above, Etherium experience the highest profit of 966% between 10-11-2020 and 09-11-21. It can also been concluded that Etherium experince the greatest loss between 10-11-2021 and 21-02-2022, which translated to 43% loss.

In [ ]:
import plotly.express as px
import plotly.graph_objects as go

fig = go.Figure()
fig.add_trace(go.Scatter(x=crypto_df.datebit, y=crypto_df.adj_closebit, name='Closing Price', line=dict(color='orange', width=2)))
fig.update_layout(title=('Bitcoin Price'),
                    xaxis_title='Year',
                   yaxis_title='Closing Price')
fig.show()

In [ ]:
fig1 = go.Figure()
fig1.add_trace(go.Scatter(x=crypto_df.datebit, y=crypto_df.adj_closeeth, name='Closing Price', line=dict(color='orange', width=2)))
fig1.update_layout(title=('Etherium Price'),
                    xaxis_title='Year',
                   yaxis_title='Closing Price')
fig1.show()